### ISSUE TITLE
got error while running

### ISSUE THREAD

**Issue by ArunTechExpert** [Appdynamics/apache-monitoring-extension#1]
We downloaded this project and deployed in Netbeans.,

We got this error:

Error: Could not find or load main class com.appdynamics.monitors.apache.ApacheStatusMonitor

Kindly say how to execute this code and test it.,

**Comment by satish-m** [comment]
Please follow the Installation steps provided in README.

**Comment by satish-m** [comment]
If you are still facing the issue please log a ticket at https://help.appdynamics.com/
